services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: sf_php
        volumes:
            - .:/var/www/pgmc/
        networks:
            - symfony

networks:
    symfony:
